kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-query
  labels:
    {{- include "chart-labels" . | nindent 4 }}
data:
  query.yaml: |-
{{- if (.Values.default_query_yaml) }}
{{- toYaml (.Values.default_query_yaml) | nindent 4 }}
{{- end }}
