apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    {{- include "chart-labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      {{- include "chart-labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}-{{ .Chart.Name }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: datasource-config
          secret:
            secretName: {{ .Chart.Name }}-datasource
            defaultMode: 0444
{{- with .Values.deployment }}
{{- with .securityContext }}
{{- with .pod }}
      securityContext:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- end }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "image-name" . }}:{{ .Values.deployment.image.tag }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy | default "IfNotPresent" }}
{{- with .Values.deployment }}
{{- with .securityContext }}
{{- with .container }}
          securityContext:
            {{- toYaml . | nindent 12 }}
{{- end }}
{{- end }}
{{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: datasource-config
              mountPath: /config
              readOnly: true
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: spring.cloud.kubernetes.enabled
              value: "true"
            - name: spring.cloud.bootstrap.enabled
              value: "true"
{{- with .Values.deployment }}
{{- with .readinessProbe }}
{{- if .enabled }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
{{- $readinessOpts := omit . "enabled" }}
{{- if not (empty $readinessOpts) }}
            {{- toYaml $readinessOpts | nindent 12 }}
{{- end }}
{{- end }}
{{- end }}
{{- with .livenessProbe }}
{{- if .enabled }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
{{- $livenessOpts := omit . "enabled" }}
{{- if not (empty $livenessOpts) }}
            {{- toYaml $livenessOpts | nindent 12 }}
{{- end }}
{{- end }}
{{- end }}
{{- with .startupProbe }}
{{- if .enabled }}
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
{{- $startupOpts := omit . "enabled" }}
{{- if not (empty $startupOpts) }}
            {{- toYaml $startupOpts | nindent 12 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}

{{- if .Values.deployment.resources  }}
          resources:
{{ .Values.deployment.resources | toYaml | indent 12 }}
{{- end }}
