kind: Secret
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-datasource
  labels:
    {{- include "chart-labels" . | nindent 4 }}
data:
  datasource.yaml: |-
{{- if (.Values.default_datasource_yaml) }}
{{- toYaml (.Values.default_datasource_yaml) | b64enc | nindent 4 }}
{{- end }}
