name: Deployment
on:
  release:
    types: [created]

jobs:
  build-with-quality-checks:
    uses: ./.github/workflows/workflow-build-with-quality-checks.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      QLTY_COVERAGE_TOKEN: ${{ secrets.QLTY_COVERAGE_TOKEN }}

  upload-release-assets-helm-chart:
    needs: build-with-quality-checks
    uses: ./.github/workflows/deploy-github-release-assets-helm-chart.yml
    secrets:
      TOKEN_TO_UPLOAD_ASSETS: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}

  publish-to-siakhooi-helm-charts:
    needs: build-with-quality-checks
    uses: ./.github/workflows/publish-to-siakhooi-helm-charts.yml
    secrets:
      PUBLISH_TO_GITHUB_REPO_TOKEN: ${{ secrets.PUBLISH_TO_GITHUB_REPO_TOKEN }}
